#!/bin/bash

#SBATCH --job-name=GPU-job
#
#SBATCH --partition=normal
#
#SBATCH --ntasks=1
#
#SBATCH --cpus-per-task=2
#
#SBATCH --gres=gpu:1
#
#SBATCH --output=slurm.out
#

mpirun -n 1 lmp -pk kokkos newton on -k on g 1 -sf kk -in copper_creep.in
